# Generated by Django 3.1.1 on 2020-10-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_records', '0002_auto_20201009_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='action',
            field=models.CharField(default='Add', max_length=50),
            preserve_default=False,
        ),
    ]
