# Generated by Django 3.1.1 on 2020-10-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='commitments',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='data_bg',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='disabilities',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='empl_status',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='func_loop_stmt',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='how_find_codeit',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='job_goal',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='laptop',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='mean_med_mode',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='os_type',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='problem_solving',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='sql_knowledge',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='time_pref',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='why_data_career',
        ),
    ]
