# Generated by Django 3.1.1 on 2020-10-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0002_auto_20201008_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrecord',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
