# Generated by Django 3.1.1 on 2020-11-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0003_auto_20201009_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='commitments',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='data_bg',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='empl_status',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='events',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='has_laptop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='how_find_codeit',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='job_goal',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='mean_med_mode',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='operating_sys',
            field=models.CharField(default='Windows', max_length=100),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='other',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='problem_solving',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='programming_exp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='sql_exp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='time_pref',
            field=models.CharField(default='Day class', max_length=50),
        ),
    ]
