# Generated by Django 3.1.1 on 2020-11-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0004_auto_20201102_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='has_laptop',
            field=models.CharField(default='Yes', max_length=20),
        ),
    ]
